list =[
        {
        question:"1950~ ()の特需により経済復興。<br>1955以降、()による()を目指す。(「」)",
        answer:"朝鮮特需、技術革新、経済成長、「もはや戦後ではない」",
    },
        {
        question:"()内閣：ソ連との国交回復()→()",
        answer:"鳩山一郎、日ソ共同宣言、国際連合",
    },
        {
        question:"()内閣：()",
        answer:"岸信介、60年安保",
    },
        {
        question:"()内閣：()",
        answer:"池田勇人、所得倍増計画",
    },
        {
        question:"高度経済成長の背景として、低価格の()、()・造船・自動車などの生産技術のなどがある",
        answer:"原油、鉄鋼",
    },
        {
        question:"高度経済成長の結果として、()の高度化が起こった",
        answer:"産業構造",
    },
        {
        question:"経済成長の長期化によって、貧富差が縮み個人消費が拡大したことによって社会階層の()、()、()の普及が起こった",
        answer:"平準化、均質化、中流意識",
    },
        {
        question:"（）地帯へ工業の集中→（）、（）などの環境の悪化→（）や環境保護活動",
        answer:"太平洋ベルト、過疎化、四大公害、消費者運動",
    },
        {
        question:"ドル＝ショックの背景:ベトナム戦争の戦費・大きな政府、日本や（）の躍進による貿易赤字",
        answer:"西ドイツ",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
    {
        question:"",
        answer:"",
    },
]
/*trmprate   start copy from right→→→→
    {
        question:"",
        answer:"",
    },
*/
let submit = document.getElementById("submit");
let sentence = document.getElementById("sentence");
let answer = document.getElementById("answer");
let next = document.getElementById("next");
let fcon = document.getElementById("firstconsole");
let scon = document.getElementById("secondconsole");
let back = document.getElementById("back");

let c=1
const len = list.length;
submit.onclick= submitf;
next.onclick = nextf;
back.onclick = backf;

function submitf(){
    answer.innerHTML = list[c-1].answer;
    submit.style.display = "none";
    next.style.display = "block";
    fcon.innerHTML="問題番号" + c;
}

function nextf(){
    c++;
    if (c > len){
        c = 1
    }
    sentence.innerHTML = list[c-1].question;//問題文の更新
    submit.style.display = "block";
    next.style.display = "none";
}

function backf(){
    c--;
    if (c < 1){
        c = len;
    }
    sentence.innerHTML = list[c-1].question;
    submit.style.display = "block";
    next.style.display = "none";
    fcon.innerHTML="問題番号" + c;
}
//preset
next.style.display = "none";
sentence.innerHTML = list[c-1].question;
scon.textContent = "問題数"+len;
answer.innerHTML = "Here display the answer of the question.";
